# Generated by Django 2.2.6 on 2019-11-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_itemvariation_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='color',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together={('item', 'name')},
        ),
        migrations.RemoveField(
            model_name='variation',
            name='size',
        ),
    ]
